class_name GalacticView
extends Control
## StarLearner v0.0.3 — Free flight through the galaxy.
## Player IS Sol. Each tap advances one CapricornusSortedae step.
## Stars move stochastically; their positions are pre-generated by star_travel.py.
##
## Data source: res://data/galactic_journey.jsonl
##   150 steps × 9 arc stars, v0.0.3:
##     • field = 1/√(1 + dist_pc/10)  — galactic mirror, not oracle
##     • spatial part normalized to unit direction (prevents far-star collapse)
##     • n_score shown live in HUD (honest state maintenance)
##
## Layout: top-down x-z plane. Sol fixed at center. Stars orbit stochastically.
## Scale: PARSECS_TO_PX px per parsec (dynamic — adjusts to keep stars visible).

signal go_home()

const JOURNEY_PATH    := "res://data/galactic_journey.jsonl"
const TWEEN_DURATION  := 0.55   ## seconds per step transition
const PARSECS_TO_PX   := 3.2    ## base scale: 1 pc = 3.2 px → 10pc star ≈ 32px from Sol
const SOL_LABEL       := "☀ Sol"
const ARC_STARS       := ["procyon","gomeisa","pollux","castor",
                           "capella","aldebaran","rigel","sirius","m44"]

var _steps: Array = []          ## Array of snapshot dicts from JSONL
var _current_step: int = 0      ## 0-indexed into _steps
var _star_nodes: Dictionary = {}  ## star_name → GalacticStarNode
var _tweens: Array = []

## HUD elements
var _step_label: Label
var _dist_label: Label
var _field_label: Label   ## v0.0.3: live n_score / field mirror readout
var _name_label: Label
var _next_btn: Button
var _home_btn: Button
var _sol_node: Node2D
var _viewport_center: Vector2

func _ready() -> void:
	set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	mouse_filter = Control.MOUSE_FILTER_IGNORE
	_load_journey()
	_build_ui()
	_build_stars()
	if _steps.size() > 0:
		_apply_step(0, false)

func set_active(on: bool) -> void:
	visible = on
	set_process(on)
	set_process_input(on)

## ─── Data loading ─────────────────────────────────────────────────────────────
func _load_journey() -> void:
	_steps.clear()
	var f := FileAccess.open(JOURNEY_PATH, FileAccess.READ)
	if f == null:
		push_error("GalacticView: cannot open " + JOURNEY_PATH)
		return
	while not f.eof_reached():
		var line := f.get_line().strip_edges()
		if line.is_empty():
			continue
		var parsed := JSON.parse_string(line)
		if parsed is Dictionary:
			_steps.append(parsed)
	f.close()

## ─── Scene construction ───────────────────────────────────────────────────────
func _build_ui() -> void:
	# Background
	var bg := ColorRect.new()
	bg.color = Color(0.02, 0.02, 0.06)
	bg.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	bg.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(bg)

	# Sol glow at center
	_sol_node = Node2D.new()
	add_child(_sol_node)

	# HUD — top bar
	var hud_top := HBoxContainer.new()
	hud_top.set_anchors_preset(Control.PRESET_TOP_WIDE)
	hud_top.position = Vector2(12, 10)
	hud_top.size = Vector2(get_viewport().size.x - 24, 40)
	hud_top.add_theme_constant_override("separation", 20)
	add_child(hud_top)

	_name_label = Label.new()
	_name_label.text = "Galactic Free Flight"
	_name_label.add_theme_font_size_override("font_size", 26)
	_name_label.add_theme_color_override("font_color", Color(0.85, 0.9, 1.0))
	hud_top.add_child(_name_label)

	var spacer := Control.new()
	spacer.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	hud_top.add_child(spacer)

	_step_label = Label.new()
	_step_label.add_theme_font_size_override("font_size", 20)
	_step_label.add_theme_color_override("font_color", Color(0.7, 0.85, 1.0))
	hud_top.add_child(_step_label)

	# HUD — bottom bar
	var hud_bot := HBoxContainer.new()
	hud_bot.set_anchors_preset(Control.PRESET_BOTTOM_WIDE)
	hud_bot.offset_top = -60
	hud_bot.position.x = 12
	hud_bot.size.x = get_viewport().size.x - 24
	hud_bot.add_theme_constant_override("separation", 16)
	add_child(hud_bot)

	_home_btn = Button.new()
	_home_btn.text = "← Home"
	_home_btn.add_theme_font_size_override("font_size", 22)
	_home_btn.pressed.connect(_on_home)
	hud_bot.add_child(_home_btn)

	_dist_label = Label.new()
	_dist_label.add_theme_font_size_override("font_size", 19)
	_dist_label.add_theme_color_override("font_color", Color(0.8, 0.9, 0.7))
	hud_bot.add_child(_dist_label)

	# v0.0.3: field mirror readout (n_score + mean field)
	_field_label = Label.new()
	_field_label.add_theme_font_size_override("font_size", 16)
	_field_label.add_theme_color_override("font_color", Color(0.5, 0.8, 0.6, 0.9))
	hud_bot.add_child(_field_label)

	var spacer2 := Control.new()
	spacer2.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	hud_bot.add_child(spacer2)

	_next_btn = Button.new()
	_next_btn.text = "Next Step →"
	_next_btn.add_theme_font_size_override("font_size", 24)
	_next_btn.pressed.connect(_on_next)
	hud_bot.add_child(_next_btn)

func _build_stars() -> void:
	for star_name in ARC_STARS:
		var node := GalacticStarNode.new()
		node.star_name = star_name
		node.visible = false
		_star_nodes[star_name] = node
		add_child(node)

## ─── Step logic ───────────────────────────────────────────────────────────────
func _apply_step(idx: int, animated: bool) -> void:
	if _steps.is_empty():
		return
	idx = clampi(idx, 0, _steps.size() - 1)
	_current_step = idx
	var snap: Dictionary = _steps[idx]

	# Cancel active tweens
	for tw in _tweens:
		if is_instance_valid(tw):
			tw.kill()
	_tweens.clear()

	var vp_size := get_viewport().size
	_viewport_center = vp_size * 0.5

	# Update Sol glyph (drawn in _draw of sol_node)
	_sol_node.position = _viewport_center

	# Update each star
	for star_name in ARC_STARS:
		var s: Dictionary = snap.get("stars", {}).get(star_name, {})
		if s.is_empty():
			continue
		var xyz: Array = s.get("xyz_pc", [0.0, 0.0, 0.0])
		var field: float = float(s.get("field", 0.05))
		var target_px := _to_screen(xyz[0], xyz[2])  # x-z top-down plane

		var node: GalacticStarNode = _star_nodes[star_name]
		node.field_strength = field
		node.visible = true

		if animated:
			var tw := create_tween()
			tw.tween_property(node, "position", target_px, TWEEN_DURATION) \
				.set_trans(Tween.TRANS_CUBIC).set_ease(Tween.EASE_IN_OUT)
			_tweens.append(tw)
		else:
			node.position = target_px

	_update_hud(snap)

func _to_screen(x_pc: float, z_pc: float) -> Vector2:
	## x-z plane, Sol at center. +x right, +z up (same as our ASCII map).
	return _viewport_center + Vector2(x_pc * PARSECS_TO_PX, -z_pc * PARSECS_TO_PX)

func _update_hud(snap: Dictionary) -> void:
	var step: int = int(snap.get("step", _current_step + 1))
	var total: int = _steps.size()
	_step_label.text = "Step %d / %d" % [step, total]

	var pxyz: Array = snap.get("player_xyz_pc", [0.0, 0.0, 0.0])
	var player_dist := sqrt(pxyz[0]*pxyz[0] + pxyz[1]*pxyz[1] + pxyz[2]*pxyz[2])
	var ly := player_dist * 3.262   # 1 pc = 3.262 ly
	_dist_label.text = "Sol: %.2f pc (%.2f ly)" % [player_dist, ly]

	# v0.0.3: compute mean field + best n_score across active stars
	var stars_snap: Dictionary = snap.get("stars", {})
	var total_field := 0.0
	var best_n := -999.0
	var best_star := ""
	var n_active := 0
	for sname in stars_snap:
		var sd: Dictionary = stars_snap[sname]
		var f := float(sd.get("field", 0.0))
		var ns := float(sd.get("n_score", -999.0))
		total_field += f
		n_active += 1
		if ns > best_n:
			best_n = ns
			best_star = sname
	var mean_field := total_field / max(1, n_active)
	if best_star != "" and best_n > -10.0:
		_field_label.text = "ρ̂ %.3f  |  field %.2f" % [best_n, mean_field]
	else:
		_field_label.text = "field %.2f" % mean_field

	var andromeda: bool = bool(snap.get("andromeda_active", false))
	if andromeda:
		_name_label.text = "🌀 Andromeda — stars reversed"
	else:
		_name_label.text = "Galactic Free Flight"

	# v0.0.3: at last step show continuation hint rather than dead button
	var at_end := (_current_step >= _steps.size() - 1)
	_next_btn.disabled = at_end
	if at_end:
		_next_btn.text = "ρ continues…"
	else:
		_next_btn.text = "Next Step →"

## ─── Input ────────────────────────────────────────────────────────────────────
func _on_next() -> void:
	if _current_step < _steps.size() - 1:
		_apply_step(_current_step + 1, true)

func _on_home() -> void:
	go_home.emit()

func _input(event: InputEvent) -> void:
	if not visible:
		return
	if event is InputEventKey and event.pressed:
		match event.keycode:
			KEY_RIGHT, KEY_SPACE, KEY_ENTER:
				_on_next()
			KEY_LEFT:
				if _current_step > 0:
					_apply_step(_current_step - 1, true)
			KEY_ESCAPE:
				_on_home()

## ─── Sol draw ─────────────────────────────────────────────────────────────────
func _draw() -> void:
	if not visible:
		return
	var cx := _viewport_center
	# Sol glow rings
	draw_circle(cx, 22.0, Color(1.0, 0.95, 0.4, 0.08))
	draw_circle(cx, 14.0, Color(1.0, 0.92, 0.3, 0.18))
	draw_circle(cx, 8.0,  Color(1.0, 0.95, 0.5, 0.7))
	draw_circle(cx, 5.0,  Color(1.0, 1.0,  0.8, 1.0))
	# Sol label
	draw_string(ThemeDB.fallback_font, cx + Vector2(10, -10), SOL_LABEL,
		HORIZONTAL_ALIGNMENT_LEFT, -1, 14, Color(1.0, 0.95, 0.6))
	# Scale bar: 50 pc
	var bar_start := cx + Vector2(-120, get_viewport().size.y * 0.5 - 90)
	var bar_end := bar_start + Vector2(50 * PARSECS_TO_PX, 0)
	draw_line(bar_start, bar_end, Color(0.6, 0.7, 0.8, 0.7), 2)
	draw_line(bar_start + Vector2(0,-4), bar_start + Vector2(0,4),
		Color(0.6,0.7,0.8,0.7), 2)
	draw_line(bar_end + Vector2(0,-4), bar_end + Vector2(0,4),
		Color(0.6,0.7,0.8,0.7), 2)
	draw_string(ThemeDB.fallback_font, bar_start + Vector2(0, 16), "50 pc",
		HORIZONTAL_ALIGNMENT_LEFT, -1, 12, Color(0.6, 0.7, 0.8, 0.7))

func _process(_delta: float) -> void:
	queue_redraw()
