class_name StarMagnitudes
extends RefCounted
## Real published V magnitudes for every star in ConstellationData.
##
## GENERATED by tools/match_star_magnitudes.py -- do not hand-edit.
## Each star was cross-matched to the HYG database (Hipparcos /
## Yale BSC / Gliese) by angular position, every match inside
## 0.08 degrees.
##
## ConstellationData's own third star value is an art brightness on a
## compressed scale, which is fine for the playground's decorative
## sky but cannot drive a physical brightness model. EarthShip needs
## stars and planets on one magnitude scale so that Venus at -3.9
## genuinely outshines Sirius at -1.5 and a fourth-magnitude star is
## a pinprick. These are the numbers that make that possible.
##
## Order matches ConstellationData._SPECS star order exactly.

const V: Dictionary = {
	"aries": [2.01, 2.64, 3.88, 3.61],
		# Hamal, Sheratan, Mesarthim (gam Ari), Bharani
	"taurus": [0.87, 1.65, 3.53, 3.65, 3.77, 2.85],
		# Aldebaran, Elnath, Ain, Prima Hyadum, Secunda Hyadum, Alcyone
	"gemini": [1.58, 1.16, 1.93, 3.50, 3.06, 2.87],
		# Castor, Pollux, Alhena, Wasat, Mebsuta, Tejat
	"cancer": [4.26, 3.94, 4.66, 3.53, 4.03],
		# Acubens, Asellus Australis, Asellus Borealis, Tarf, 48Iot Cnc
	"leo": [1.36, 2.14, 2.01, 2.56, 3.33, 3.43, 2.97],
		# Regulus, Denebola, Algieba, Zosma, Chertan, Adhafera, Ras Elased Australis
	"virgo": [0.98, 2.74, 2.85, 3.39, 3.38, 3.59],
		# Spica, Porrima, Vindemiatrix, Minelauva, Heze, Zavijava
	"libra": [2.75, 2.61, 3.25, 3.91],
		# Zubenelgenubi, Zubeneschamali, Brachium, Zubenelhakrabi
	"scorpio": [1.06, 2.56, 2.29, 1.62, 2.70, 1.86, 2.82, 2.89],
		# Antares, Acrab, Dschubba, Shaula, Lesath (ups Sco), Sargas, Paikauhale, Fang
	"sagittarius": [1.79, 2.72, 2.82, 2.05, 2.60, 2.88, 3.17],
		# Kaus Australis, Kaus Media, Kaus Borealis (lam Sgr), Nunki, Ascella, Albaldah, 27Phi Sgr
	"capricorn": [2.85, 3.05, 3.69, 4.30, 4.12],
		# Deneb Algedi, Dabih, Nashira, 5Alp1Cap, 18Ome Cap
	"aquarius": [2.95, 2.90, 3.73, 3.27, 3.78],
		# Sadalmelik, Sadalsuud, lambda Aqr, Skat, Albali (eps Aqr)
	"pisces": [3.82, 3.70, 3.62, 4.03, 4.45, 4.27],
		# Alrescha, 6Gam Psc, Alpherg, 28Ome Psc, nu Psc, 10The Psc
	"orion": [0.45, 1.64, 1.69, 1.74, 2.25, 0.18, 2.07, 3.39],
		# Betelgeuse, Bellatrix, Alnilam, Alnitak, Mintaka, Rigel, Saiph, Meissa
	"lepus": [2.58, 2.84, 3.19, 3.55, 3.71, 4.29],
		# Arneb (alpha Lep), Nihal (beta Lep), epsilon Lep, mu Lep, zeta Lep, gamma Lep
	"ursa_major": [1.81, 2.34, 2.41, 3.32, 1.76, 2.23, 1.85],
		# Dubhe, Merak, Phecda, Megrez, Alioth, Mizar, Alkaid
	"cassiopeia": [2.28, 2.24, 2.15, 2.66, 3.35],
		# Caph, Schedar, Cih, Ruchbah, Segin
	"cygnus": [1.25, 2.23, 2.48, 2.86, 3.05],
		# Deneb, Sadr, Aljanah, Fawaris, Albireo
	"lyra": [0.03, 3.52, 3.25, 4.34, 4.22],
		# Vega, Sheliak, Sulafat, 6Zet1Lyr, delta2 Lyr
	"aquila": [0.76, 2.72, 3.71, 3.24, 3.36],
		# Altair, Tarazed, Alshain, 65The Aql, 30Del Aql
	"pegasus": [2.49, 2.44, 2.83, 2.07, 2.38],
		# Markab, Scheat, Algenib, Alpheratz, Enif
	"andromeda": [2.07, 2.07, 2.10, 3.27],
		# Alpheratz, Mirach, Almach, 31Del And
	"perseus": [1.79, 2.09, 3.84, 2.90, 3.01],
		# Mirfak, Algol, Atik, epsilon Per, 39Del Per
	"canis_major": [-1.44, 1.50, 1.83, 2.45, 1.98],
		# Sirius, Adhara, Wezen, Aludra, Mirzam
	"canis_minor": [0.40, 2.89, 4.99, 5.22],
		# Procyon, Gomeisa, epsilon CMi, eta CMi
	"bootes": [-0.05, 2.35, 3.04, 3.49, 2.68],
		# Arcturus, Izar, Seginus, Nekkar, Muphrid
	"auriga": [0.08, 1.90, 2.65, 3.03, 2.69],
		# Capella, Menkalinan, Mahasim, Almaaz (eps Aur), Hassaleh
	# ── Southern and extended sky ─────────────────────────────────────────────
	"crux": [0.77, 1.25, 1.59, 2.79],
		# Acrux, Mimosa/Becrux, Gacrux, delta Cru
	"hydra": [4.16, 3.38, 3.11, 4.30, 1.98, 3.11, 3.11, 4.29],
		# delta Hya, eps Hya (head), zet Hya (neck), eta Hya (head),
		# Alphard (alpha Hya, brightest), mu Hya, nu Hya, beta Hya (tail)
	"monoceros": [3.93, 3.70, 3.98, 4.15, 4.39, 4.36],
		# alpha Mon, beta Mon, gamma Mon, delta Mon, eps Mon, zet Mon
	"corvus": [4.02, 2.65, 2.59, 2.95, 3.00],
		# Alchiba, Kraz, Gienah, Algorab, eps Crv
	"centaurus": [-0.27, 0.61, 2.31, 2.55, 2.30, 2.20],
		# Rigil Kent (alpha Cen), Hadar (beta Cen), eta Cen, zeta Cen, eps Cen, gamma Cen
	"ophiuchus": [2.08, 2.77, 2.74, 3.24, 2.54, 2.43, 3.19],
		# Rasalhague, Cebalrai, Yed Prior, Yed Post, zet Oph, Sabik, kap Oph
	"hercules": [3.48, 2.77, 3.75, 3.14, 3.92, 2.81, 3.53, 3.16],
		# Rasalgethi, Kornephoros, gamma Her, delta Her, eps Her,
		# zet Her (Keystone NW), eta Her (Keystone NE), pi Her (Keystone SE)
}

## V magnitudes for a constellation id, or an empty array.
static func for_id(id: String) -> Array:
	return V.get(id, [])

## V magnitude of one star, or a faint default when unknown.
static func of(id: String, index: int) -> float:
	var a: Array = V.get(id, [])
	if index < 0 or index >= a.size():
		return 6.0
	return float(a[index])
