#!/usr/bin/env bash
# Deploy starlearner.dylanmccapes.systems — nginx vhost + bearer map + landing.
#
# Run:  sudo bash deploy/deploy.sh
#
# Does NOT start the ASR backend (user systemd unit; notes at the end).
# Nginx proxies /api/asr/* → 127.0.0.1:8770 behind the hub bearer token.
set -euo pipefail

if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  echo "Run with sudo:  sudo bash $0"
  exit 1
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WWW=/var/www/starlearner
SITE=starlearner.dylanmccapes.systems
OWNER=dylanmccapes
OWNER_HOME="$(getent passwd "$OWNER" | cut -d: -f6)"
INDEX="$ROOT/deploy/www-index.html"
NGINX_SRC="$ROOT/deploy/nginx-starlearner.conf"
TOKEN_FILE="$ROOT/ant_explorer/tools/secrets/hub245/token.txt"
TOKENS_DST=/etc/nginx/conf.d/starlearner-asr-tokens.conf

HTPASSWD=/etc/nginx/nakatomi.htpasswd

[[ -f "$INDEX" ]]     || { echo "Missing $INDEX" >&2; exit 1; }
[[ -f "$NGINX_SRC" ]] || { echo "Missing $NGINX_SRC" >&2; exit 1; }
[[ -f "$TOKEN_FILE" ]] || {
  echo "Missing hub bearer token at $TOKEN_FILE" >&2
  exit 1
}
[[ -f /etc/ssl/cloudflare/origin.pem ]] || {
  echo "Missing Cloudflare Origin CA cert at /etc/ssl/cloudflare/origin.pem" >&2
  exit 1
}
[[ -f "$HTPASSWD" ]] || {
  echo "Missing $HTPASSWD (shared basic-auth across dylanmccapes.systems)" >&2
  exit 1
}

# nginx workers must read htpasswd for /logs/
chown root:www-data "$HTPASSWD"
chmod 640 "$HTPASSWD"

TOKEN="$(tr -d ' \t\r\n' < "$TOKEN_FILE")"
[[ ${#TOKEN} -ge 32 ]] || { echo "Token too short in $TOKEN_FILE" >&2; exit 1; }

echo "▸ Publishing site → $WWW"
install -d -m 755 -o www-data -g www-data "$WWW"
install -m 644 -o www-data -g www-data "$INDEX" "$WWW/index.html"

echo "▸ Installing bearer map → $TOKENS_DST"
# Do NOT set map_hash_bucket_size here — nakatomi-mcp-tokens.conf already does.
cat >"$TOKENS_DST" <<EOF
# Star Learner ASR — bearer tokens (http-level map).
# Regenerated by star_learning/deploy/deploy.sh from hub245/token.txt.
# Revoke: rotate token.txt, re-run deploy.sh, rebuild Language APK.
map \$http_authorization \$asr_token_ok {
    default 0;
    "Bearer ${TOKEN}" 1;
}
EOF
chmod 644 "$TOKENS_DST"

echo "▸ Installing nginx vhost $SITE"
install -m 644 "$NGINX_SRC" "/etc/nginx/sites-available/$SITE"
ln -sf "/etc/nginx/sites-available/$SITE" "/etc/nginx/sites-enabled/$SITE"

if [[ -n "$OWNER_HOME" ]]; then
  install -d -m 755 -o "$OWNER" -g "$OWNER" "$OWNER_HOME/.nakatomi-secrets/nginx"
  install -m 644 -o "$OWNER" -g "$OWNER" "$NGINX_SRC" \
    "$OWNER_HOME/.nakatomi-secrets/nginx/$SITE"
fi

echo "▸ nginx -t && reload"
nginx -t
systemctl reload nginx

echo ""
echo "✓ nginx live for https://$SITE/"
echo "  Static:  $WWW/index.html"
echo "  Config:  /etc/nginx/sites-available/$SITE"
echo "  Auth:    $TOKENS_DST"
echo "  Proxy:   /api/asr/* → 127.0.0.1:8770"
echo "  Logs:    /logs/ → 127.0.0.1:8771 (basic auth via $HTPASSWD)"
echo "  Ops:     /ops/  → fogona APK queue + Deliver now (same auth)"
echo "  Queue:   ./tools/queue_fogona_deliver.sh garden   # stage only"
echo "  Deliver: press Deliver now on /ops/ when 245 is up (no polling)"
echo ""
echo "Backend (run as $OWNER, not root):"
echo "  # stop any ad-hoc ASR on :8770 first"
echo "  fuser -k 8770/tcp 2>/dev/null || true"
echo "  cp $ROOT/deploy/starlearner-asr.service ~/.config/systemd/user/"
echo "  cp $ROOT/deploy/starlearner-logs.service ~/.config/systemd/user/"
echo "  cp $ROOT/deploy/starlearner-fogona-queue.service ~/.config/systemd/user/"
echo "  systemctl --user daemon-reload"
echo "  systemctl --user enable --now starlearner-asr starlearner-logs"
echo "  # fogona queue starts when you: ./tools/queue_fogona_deliver.sh garden --build"
echo "  # once: sudo loginctl enable-linger $OWNER"
echo ""
echo "DNS: Cloudflare A record 'starlearner' → this box's public IPv4 (73.12.211.52),"
echo "     Proxied (orange cloud). Zone SSL = Full (strict)."
echo "Verify:  curl -sI https://$SITE/ | head -5"
echo "         curl -s -H \"Authorization: Bearer \\\$(cat $TOKEN_FILE)\" https://$SITE/api/asr/health"
echo "         curl -sI -u dylan:PASSWORD https://$SITE/logs/ | head -5"
echo "         curl -sI -u dylan:PASSWORD https://$SITE/ops/ | head -5"
