#!/usr/bin/env python3
"""Key the flat-magenta window of a generated cockpit frame to transparent.

The cockpit art (game/images/cockpit.png) is generated by an agent with its
window opening filled a flat chroma magenta (#FF00FF) so the live 3D scene can
show through it at runtime. This turns that magenta region into alpha=0 while
leaving the frame, dashboard, and colored buttons untouched.

Usage:
    python3 tools/key_cockpit.py [SRC_PNG] [OUT_PNG]

Defaults: SRC = <repo>/../.cursor .../assets/cockpit_raw.png-style input passed
in explicitly; OUT = game/images/cockpit.png. Re-runnable / idempotent.
"""
import sys
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO / "game" / "images" / "cockpit.png"


def is_magenta(r: int, g: int, b: int) -> bool:
    # Chroma window: red and blue high, green clearly lower. Captures the whole
    # magenta gradient without touching cream frame (all channels high), orange
    # (low blue), blue (low red), green/yellow buttons (low blue or low red).
    return r > 150 and b > 150 and g < min(r, b) - 60


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: key_cockpit.py SRC_PNG [OUT_PNG]", file=sys.stderr)
        return 2
    src = Path(sys.argv[1])
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT
    out.parent.mkdir(parents=True, exist_ok=True)

    img = Image.open(src).convert("RGBA")
    px = img.load()
    w, h = img.size
    keyed = 0
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if is_magenta(r, g, b):
                px[x, y] = (0, 0, 0, 0)
                keyed += 1
    img.save(out)
    pct = 100.0 * keyed / (w * h)
    print(f"keyed {keyed} px ({pct:.1f}%) -> {out}  ({w}x{h})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
